var quotes = [
'“When you want to succeed as bad as you want to breathe, then you’ll be successful.” – Eric Thomas ',
'“Whatever the mind can think and perceive, it can achieve. – Napolean Hill',
'“It doesn’t matter how slowly you go, as long as you don’t stop.” – Confucious',
'“What you do today can improve all of your tomorrows.” – Ralph Marston',
'“Wake up determined go to bed satisfied.” – Dwayne Johnson',
'“You begin by always expecting good things to happen.” – Tom Hopkins',
'“It always seems impossible until it’s done.” – Nelson Mandela',
'“Don’t stop when you’re tired. Stop when you are done.”',
'“Don’t limit your challenges, challenge your limits.”',
'“The most common way for people to give up their power is by thinking they don’t have any.” – Alice Walker',
'“Don’t be afraid to give up the good for the great.” – John Rockefeller',
'“We are all a little broken, but last time I checked, broken crayons still color the same.”',
'“If you want to be successful, prepare to be doubted and tested.”',
'“Vision is the art of seeing what is invisible to others.” – Johnathan Swift',
'“We can do no great things, only small things with great love.” – Mother Theresa',
'“Don’t let what you cannot do interfere with what you can do.” – John Wooden',
'“Just because my path is different doesn’t mean I’m lost.”',
'“Innovation distinguishes between a leader and a follower.”',
'“I am not afraid of storms because I am learning how to sail my ship.” – Louisa May Alocott',
'“Leadership is the ability to get extraordinary achievement from ordinary people.” – Brian Tracy',
'“Never regret a day of your life. Good days give you happiness. Bad days give you experience.”',
'“To accomplish great things, we must not only act, but also dream. Not only plan but also believe.” – Anatole France',
'“All journeys have secret destinations of which the travelers is unaware.” – Marin Buber',
'“Love your enemies because they tell you all your faults.” – Benjamin Franklin',
'“If’I had six hours to chop down a tree, I would spend the first four hours sharpening the axe.” – Abraham Lincoln',
'“Leap and the net will appear.” – John Burroughs',
'“You words can be powerful, they can hurt or uplift you, so think before you speak as every word counts.”',
'“It’s not the load that keeps you down, it’s how you carry it.” – Lou Holtz',
'“Your mind is a powerful thing. When you fill it with positive thoughts, your life will start to change.” – Unknown',
'“When your work speaks for itself, don’t interrupt.” – Henry Kaiser',
'“Be patient with yourself. Self-growth is tender, it’s holy ground. There is no greater investment.” – Stephen Covey',
'“Knowing is not enough we must apply. Wishing is not enough, we must do.” – Johann Wolfgang',
'“Good, better, best. Never let it rest. Til your good is better and your better is best.” – Jerome',
'“Remember, no one can make you feel inferior without your consent.” – Eleanor Rosevelt',
'“What comes easy won’t last and what lasts won’t come easy.”',
'“Challenge yourself. It’s the only path to growth.” – Morgan Freeman',
'“Just when the caterpillar thought the world was ending, he turned into a butterfly.” – Proverb',
'“To live a creative life, we must lose our fear of being wrong.” – John Wooden',
'“People say motivation doesn’t last. Well neither does bathing. That’s why we recommend it daily.” – Zig Ziglar',
]

function newQuote() {
var randomNumber = Math.floor(Math.random() * (quotes.length));
document.getElementById('quoteDisplay').innerHTML = quotes[randomNumber];
}